In [3]:
import numpy as np

In [7]:
arr4 = np.arange(1,10).reshape(3,3)
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.linspace(1,10,12,dtype=int).reshape(3,4)

array([[ 1,  1,  2,  3],
       [ 4,  5,  5,  6],
       [ 7,  8,  9, 10]])

In [12]:
np.random.rand(3, 3)*10

array([[6.07425848, 4.32537865, 9.61222561],
       [4.84468218, 1.36283762, 9.4640523 ],
       [5.1853487 , 1.51239543, 0.55144949]])

In [18]:
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
ones = np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
a = np.arange(1,9).reshape(2,4)
b = np.arange(9,17).reshape(2,4)

In [25]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
b

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [27]:
a+b

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [28]:
a*b

array([[  9,  20,  33,  48],
       [ 65,  84, 105, 128]])

In [32]:
c = np.arange(1,9).reshape(4,2)
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [33]:
a.dot(c)

array([[ 50,  60],
       [114, 140]])

In [34]:
a**2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [35]:
10*np.sin(a)

array([[ 8.41470985,  9.09297427,  1.41120008, -7.56802495],
       [-9.58924275, -2.79415498,  6.56986599,  9.89358247]])

In [36]:
a>5

array([[False, False, False, False],
       [False,  True,  True,  True]])

In [37]:
a@c

array([[ 50,  60],
       [114, 140]])

In [40]:
d=np.random.random((2,3))

In [41]:
d

array([[0.63618884, 0.03248451, 0.18741561],
       [0.4982141 , 0.42448523, 0.50262114]])

In [42]:
# indexing and slicing

In [43]:
myarray = np.arange(1,17).reshape(4,4)

In [44]:
myarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [45]:
myarray[2]

array([ 9, 10, 11, 12])

In [51]:
myarray[2][2]

np.int64(11)

In [64]:
myarray[2:4,2:4].flatten()

array([11, 12, 15, 16])

In [67]:
myarray[2:,1:]

array([[10, 11, 12],
       [14, 15, 16]])

In [82]:
e = np.floor(10*np.random.random((2,2)))
f = np.floor(10*np.random.random((2,2)))

In [83]:
np.vstack((e,f))

array([[6., 9.],
       [8., 9.],
       [5., 8.],
       [8., 4.]])

In [84]:
np.hstack((e,f))

array([[6., 9., 5., 8.],
       [8., 9., 8., 4.]])

In [87]:
np.hsplit(e,2)

[array([[6.],
        [8.]]),
 array([[9.],
        [9.]])]

In [5]:
g = np.arange(1,10).reshape(3,3)
g

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
bool_arr = g%2==0
bool_arr

array([False,  True, False,  True, False,  True, False,  True, False])

In [92]:
g[bool_arr]

array([2, 4, 6, 8])

In [99]:
g.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [100]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [6]:
np.diagonal(g)

array([1, 5, 9])

In [7]:
np.trace(g)

np.int64(15)